# Generated by Django 5.0.7 on 2024-08-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortreviewscrap',
            name='review',
        ),
        migrations.RemoveField(
            model_name='shortreviewscrap',
            name='user',
        ),
        migrations.DeleteModel(
            name='LongReviewScrap',
        ),
        migrations.DeleteModel(
            name='ShortReviewScrap',
        ),
    ]
