# Generated by Django 5.0.7 on 2024-07-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('thumbnail', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READING', 'Reading'), ('READ', 'Read'), ('WISH', 'Wish')], default='WISH', max_length=128)),
                ('totalpage', models.IntegerField()),
                ('readpage', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
