# Generated by Django 5.0.7 on 2024-07-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mybook',
            table='mybooks',
        ),
    ]
