# Generated by Django 5.0.7 on 2024-07-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='status',
            field=models.CharField(choices=[('지금 읽고 있는 책', 'Reading'), ('지금까지 읽은 책', 'Read'), ('찜해둔 책', 'Wish')], default='찜해둔 책', max_length=128),
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readcount', models.IntegerField()),
                ('readingcount', models.IntegerField()),
                ('wishcount', models.IntegerField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('mybook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.mybook')),
            ],
        ),
    ]
