# Generated by Django 5.0.7 on 2024-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_mybook_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='mybooks',
            field=models.ManyToManyField(related_name='desks', to='books.mybook'),
        ),
    ]
