# Generated by Django 5.0.7 on 2024-07-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_mybook_status_desk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybook',
            name='readpage',
        ),
        migrations.RemoveField(
            model_name='mybook',
            name='totalpage',
        ),
    ]
