# Generated by Django 5.0.7 on 2024-07-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_mybook_readpage_remove_mybook_totalpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desk',
            old_name='readcount',
            new_name='read_count',
        ),
        migrations.RenameField(
            model_name='desk',
            old_name='readingcount',
            new_name='reading_count',
        ),
        migrations.RenameField(
            model_name='desk',
            old_name='wishcount',
            new_name='wish_count',
        ),
    ]
