# Generated by Django 5.0.7 on 2024-07-29 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_desk_mybooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='deskdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
