# Generated by Django 5.0.7 on 2024-07-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_readcount_desk_read_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='mybook',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='reading_count',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='wish_count',
        ),
        migrations.AddField(
            model_name='desk',
            name='mybooks',
            field=models.ManyToManyField(to='books.mybook'),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='status',
            field=models.CharField(choices=[('지금 읽고 있는 책', 'reading'), ('지금까지 읽은 책', 'read'), ('찜해둔 책', 'wish')], default='찜해둔 책', max_length=128),
        ),
        migrations.AlterModelTable(
            name='desk',
            table='desks',
        ),
    ]
