# Generated by Django 5.0.7 on 2024-07-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_desk_mybook_remove_desk_read_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='status',
            field=models.CharField(choices=[('reading', 'Reading'), ('read', 'Read'), ('wish', 'Wish')], default='wish', max_length=128),
        ),
    ]
