# Generated by Django 5.0.7 on 2024-07-27 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongReview',
            fields=[
                ('long_review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('review_title', models.CharField(max_length=30)),
                ('long_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open', models.BooleanField(default=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('my_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.mybook')),
            ],
        ),
        migrations.CreateModel(
            name='ShortReview',
            fields=[
                ('short_review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('mood', models.CharField(choices=[('worried', '걱정돼요'), ('tired', '피곤해요'), ('sad', '슬퍼요'), ('good', '좋아요'), ('okay', '괜찮아요')], max_length=10)),
                ('question', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=300)),
                ('short_comment', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open', models.BooleanField(default=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('my_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.mybook')),
            ],
        ),
    ]
