# Generated by Django 5.0.7 on 2024-08-02 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_mybook_deskdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LongReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.PositiveIntegerField()),
                ('end_page', models.PositiveIntegerField()),
                ('read_complete', models.BooleanField(default=False)),
                ('review_title', models.CharField(max_length=255)),
                ('long_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('open', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_count', models.PositiveIntegerField(default=0)),
                ('okay_count', models.PositiveIntegerField(default=0)),
                ('tired_count', models.PositiveIntegerField(default=0)),
                ('sad_count', models.PositiveIntegerField(default=0)),
                ('worried_count', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.PositiveIntegerField()),
                ('end_page', models.PositiveIntegerField()),
                ('read_complete', models.BooleanField(default=False)),
                ('mood', models.CharField(choices=[('good', '좋아요'), ('okay', '괜찮아요'), ('tired', '피곤해요'), ('sad', '슬퍼요'), ('worried', '걱정돼요')], max_length=10)),
                ('question', models.CharField(choices=[('오늘 읽은 책이 나에게 어떤 도움이 될 수 있을까요?', '오늘 읽은 책이 나에게 어떤 도움이 될 수 있을까요?'), ('책을 읽으면서 떠오른 나의 개인적인 경험이나 기억은 무엇인가요?', '책을 읽으면서 떠오른 나의 개인적인 경험이나 기억은 무엇인가요?'), ('이 책을 읽으면서 가장 강렬하게 느꼈던 감정은 무엇인가요?', '이 책을 읽으면서 가장 강렬하게 느꼈던 감정은 무엇인가요?'), ('이 책이 나의 희망이나 두려움에 어떤 영향을 주었나요?', '이 책이 나의 희망이나 두려움에 어떤 영향을 주었나요?'), ('책의 내용을 통해 느낀 위로나 치유는 무엇인가요?', '책의 내용을 통해 느낀 위로나 치유는 무엇인가요?'), ('이 책이 나의 가치관이나 신념에 어떤 영향을 미쳤나요?', '이 책이 나의 가치관이나 신념에 어떤 영향을 미쳤나요?')], max_length=255)),
                ('answer', models.CharField(max_length=300)),
                ('short_comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('open', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
