# Generated by Django 5.0.7 on 2024-08-02 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_mybook_deskdate'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.mybook'),
        ),
        migrations.AlterField(
            model_name='moodcount',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.mybook'),
        ),
        migrations.AlterField(
            model_name='shortreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.mybook'),
        ),
    ]
