# Generated by Django 5.0.7 on 2024-08-03 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_mybook_deskdate'),
        ('notes', '0002_alter_longreview_book_alter_moodcount_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortreview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='shortreview',
            name='member',
        ),
        migrations.RenameField(
            model_name='longreview',
            old_name='review_title',
            new_name='long_title',
        ),
        migrations.RenameField(
            model_name='longreview',
            old_name='member',
            new_name='writer',
        ),
        migrations.AddField(
            model_name='longreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='longreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='longreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='longreview',
            table='long_reviews',
        ),
        migrations.DeleteModel(
            name='MoodCount',
        ),
        migrations.DeleteModel(
            name='ShortReview',
        ),
    ]
