# Generated by Django 5.0.7 on 2024-08-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_shortreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortreview',
            name='mood',
            field=models.CharField(choices=[('good', 'Good'), ('okay', 'Okay'), ('tired', 'Tired'), ('sad', 'Sad'), ('worried', 'Worried')], max_length=10),
        ),
    ]
