# Generated by Django 5.0.7 on 2024-08-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_shortreview_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortreview',
            name='long_text',
        ),
        migrations.RemoveField(
            model_name='shortreview',
            name='long_title',
        ),
        migrations.AlterField(
            model_name='shortreview',
            name='answer',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='shortreview',
            name='short_comment',
            field=models.CharField(max_length=300),
        ),
    ]
