# Generated by Django 5.0.7 on 2024-08-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_shortreview_long_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longreview',
            name='open',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='longreview',
            name='read_complete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='shortreview',
            name='read_complete',
            field=models.BooleanField(),
        ),
    ]
