# Generated by Django 5.0.7 on 2024-08-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_longreview_open_alter_longreview_read_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longreview',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
