# Generated by Django 5.0.7 on 2024-07-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worry', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WorryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('worry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.worry')),
            ],
        ),
    ]
